/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dam.programacion.juanminm.u12;

/**
 *
 * @author Juan Miguel Navarro Martínez
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora2
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        NumSysRBGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        InputField = new javax.swing.JTextField();
        toDecButton = new javax.swing.JButton();
        toBinButton = new javax.swing.JButton();
        toOctButton = new javax.swing.JButton();
        toHexButton = new javax.swing.JButton();
        OutputField = new javax.swing.JTextField();
        DecRButton = new javax.swing.JRadioButton();
        OctRButton = new javax.swing.JRadioButton();
        BinRButton = new javax.swing.JRadioButton();
        HexRButton3 = new javax.swing.JRadioButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Calculadora");

        InputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        toDecButton.setText("DEC");
        toDecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toDecButtonActionPerformed(evt);
            }
        });

        toBinButton.setText("BIN");
        toBinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBinButtonActionPerformed(evt);
            }
        });

        toOctButton.setText("OCT");
        toOctButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toOctButtonActionPerformed(evt);
            }
        });

        toHexButton.setText("HEX");
        toHexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toHexButtonActionPerformed(evt);
            }
        });

        OutputField.setEditable(false);
        OutputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        NumSysRBGroup.add(DecRButton);
        DecRButton.setText("Dec");
        DecRButton.setActionCommand("dec");

        NumSysRBGroup.add(OctRButton);
        OctRButton.setText("Oct");
        OctRButton.setActionCommand("oct");

        NumSysRBGroup.add(BinRButton);
        BinRButton.setText("Bin");
        BinRButton.setActionCommand("bin");

        NumSysRBGroup.add(HexRButton3);
        HexRButton3.setText("Hex");
        HexRButton3.setActionCommand("hex");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toDecButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toOctButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toBinButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toHexButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(OutputField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputField)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(DecRButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BinRButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OctRButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HexRButton3)))))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BinRButton)
                    .addComponent(OctRButton)
                    .addComponent(DecRButton)
                    .addComponent(HexRButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toDecButton)
                    .addComponent(toBinButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toOctButton)
                    .addComponent(toHexButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OutputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private long convertNumber(String input) throws NumberFormatException,
            NullPointerException {
        int radix;

        switch (NumSysRBGroup.getSelection().getActionCommand()) {
            case "bin":
                radix = 2;
                break;
            case "oct":
                radix = 8;
                break;
            case "dec":
                radix = 10;
                break;
            case "hex":
                radix = 16;
                break;
            default:
                radix = 10;
        }

        return Long.valueOf(input, radix);
    }

    private void toOctButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toOctButtonActionPerformed
        String input = InputField.getText();

        try {
            String output = Long.toOctalString(convertNumber(input));
            OutputField.setText(output);
        } catch (NumberFormatException | NullPointerException ex) {
            OutputField.setText("ERROR");
        }
    }//GEN-LAST:event_toOctButtonActionPerformed

    private void toDecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toDecButtonActionPerformed
        String input = InputField.getText();

        try {
            String output = Long.toString(convertNumber(input));
            OutputField.setText(output);
        } catch (NumberFormatException | NullPointerException ex) {
            OutputField.setText("ERROR");
        }
    }//GEN-LAST:event_toDecButtonActionPerformed

    private void toBinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBinButtonActionPerformed
        String input = InputField.getText();

        try {
            String output = Long.toBinaryString(convertNumber(input));
            OutputField.setText(output);
        } catch (NumberFormatException | NullPointerException ex) {
            OutputField.setText("ERROR");
        }
    }//GEN-LAST:event_toBinButtonActionPerformed

    private void toHexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toHexButtonActionPerformed
        String input = InputField.getText();

        try {
            String output = Long.toHexString(convertNumber(input));
            OutputField.setText(output);
        } catch (NumberFormatException | NullPointerException ex) {
            OutputField.setText("ERROR");
        }
    }//GEN-LAST:event_toHexButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BinRButton;
    private javax.swing.JRadioButton DecRButton;
    private javax.swing.JRadioButton HexRButton3;
    private javax.swing.JTextField InputField;
    private javax.swing.ButtonGroup NumSysRBGroup;
    private javax.swing.JRadioButton OctRButton;
    private javax.swing.JTextField OutputField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton toBinButton;
    private javax.swing.JButton toDecButton;
    private javax.swing.JButton toHexButton;
    private javax.swing.JButton toOctButton;
    // End of variables declaration//GEN-END:variables
}
