package dam.programacion.juanminm.u12;

import java.util.Calendar;
import java.util.Locale;
import java.util.TimeZone;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Juan Miguel Navarro Martínez
 */
public class FechaHora extends javax.swing.JFrame {

    /**
     * Creates new form FechaHora
     */
    public FechaHora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FechaHoraLabel = new javax.swing.JLabel();
        TextLabel1 = new javax.swing.JLabel();
        TextLabel2 = new javax.swing.JLabel();
        FechaLabel = new javax.swing.JLabel();
        HoraLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        FechaHoraLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        FechaHoraLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FechaHoraLabel.setText("Fecha y Hora");

        TextLabel1.setText("La fecha es:");

        TextLabel2.setText("La hora es:");

        FechaLabel.setText("Fecha");

        HoraLabel.setText("Hora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaHoraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextLabel1)
                            .addComponent(TextLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoraLabel)
                            .addComponent(FechaLabel))
                        .addGap(0, 234, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FechaHoraLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextLabel1)
                    .addComponent(FechaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextLabel2)
                    .addComponent(HoraLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TimeZone zone = TimeZone.getTimeZone("CET");
        Calendar c1 = Calendar.getInstance(zone);

        String horasYMinutos = String.format("%02d:%02d", c1.get(Calendar.HOUR_OF_DAY),
                c1.get(Calendar.MINUTE));
        String horaCompleta = String.format("%s:%02d", horasYMinutos, c1.get(Calendar.SECOND));


        int dia = c1.get(Calendar.DAY_OF_MONTH);
        String diaSemana = c1.getDisplayName(Calendar.DAY_OF_WEEK,
                Calendar.SHORT, Locale.getDefault());
        int mes = c1.get(Calendar.MONTH) + 1;
        String mesEscrito = c1.getDisplayName(Calendar.MONTH, Calendar.SHORT,
                Locale.getDefault());
        int año = c1.get(Calendar.YEAR);

        FechaHoraLabel.setText(diaSemana + " " + mesEscrito + " " + dia + " "
                + horaCompleta + " " + zone.getID()
                + " " + año);
        FechaLabel.setText(dia + " de " + mes + " de " + año);
        HoraLabel.setText(horasYMinutos);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FechaHora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FechaHora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FechaHora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FechaHora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FechaHora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaHoraLabel;
    private javax.swing.JLabel FechaLabel;
    private javax.swing.JLabel HoraLabel;
    private javax.swing.JLabel TextLabel1;
    private javax.swing.JLabel TextLabel2;
    // End of variables declaration//GEN-END:variables
}
